apiVersion: v1
kind: Namespace
metadata:
  name: genai-chatbot
  labels:
    name: genai-chatbot
    app: genai-chatbot
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: genai-chatbot-quota
  namespace: genai-chatbot
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: genai-chatbot-limits
  namespace: genai-chatbot
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
